### ISSUE TITLE
[Enhancement] Add Pairing Feature

### ISSUE THREAD

**Issue by minkione** [hackgnar/ble_ctf#2]
Hi,
Was just thinking about another level to add to the CTF: Add Pairing Feature. [e.g (1)]
Maybe with two different types: All Zeroes and Random PIN.

Thus players can also try to crack the TK with crackle ;]

(1) https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_security_server/tutorial/Gatt_Security_Server_Example_Walkthrough.md

**Comment by hackgnar** [comment]
I considered it for this version of the CTF but decided not to implement it.  It will be in a later version coming soon =)
